/*
 * LoginFlow — auto-generated by Mobile Test Recorder.
 * Generated login flow used for golden tests.
 * App under test: com.example.app
 * DO NOT EDIT BY HAND — regenerate from the recorded flow instead.
 */
package generated;

import io.appium.java_client.AppiumBy;
import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.android.options.UiAutomator2Options;
import org.openqa.selenium.By;
import org.openqa.selenium.NoSuchElementException;
import org.openqa.selenium.WebElement;
import org.testng.Assert;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import java.net.URL;
import java.time.Duration;

public class LoginFlow {

    private AndroidDriver driver;

    @BeforeMethod
    public void setUp() throws Exception {
        UiAutomator2Options options = new UiAutomator2Options();
        options.setPlatformName("Android");
        options.setAppPackage("com.example.app");
        options.setAppActivity(".MainActivity");
        driver = new AndroidDriver(new URL("http://localhost:4723"), options);
    }

    @AfterMethod
    public void tearDown() {
        if (driver != null) {
            driver.quit();
        }
    }

    /** Locate an element, falling back through ranked alternatives (self-healing). */
    private WebElement find(By primary, By[] fallbacks) {
        try {
            return driver.findElement(primary);
        } catch (NoSuchElementException ignored) {
        }
        for (By by : fallbacks) {
            try {
                return driver.findElement(by);
            } catch (NoSuchElementException ignored) {
            }
        }
        throw new NoSuchElementException("No locator matched (primary + " + fallbacks.length + " fallbacks)");
    }

    @Test
    public void login() {
        // Open app
        driver.activateApp("com.example.app");
        // Enter email
        find(AppiumBy.id("user_field"), new By[]{AppiumBy.xpath("//input[1]")}).sendKeys("alice@example.com");
        // Tap login
        find(AppiumBy.accessibilityId("login_btn"), new By[]{}).click();
        // Wait for home
        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
        // Dismiss a dialog
        driver.navigate().back();
        // Welcome message shown
        Assert.assertTrue(find(AppiumBy.androidUIAutomator("new UiSelector().text(\"Welcome\")"), new By[]{}).isDisplayed());
    }

}
