/*
 * Step definitions for LoginFlow — auto-generated by Mobile Test Recorder.
 * Generated login flow used for golden tests.
 * Cucumber.js + WebdriverIO. The `driver`/`expect` globals come from the
 * WebdriverIO cucumber framework adapter.
 * DO NOT EDIT BY HAND — regenerate from the recorded flow instead.
 */

const { Given, When, Then } = require('@cucumber/cucumber');

const APP_PACKAGE = 'com.example.app';

// Friendly target name -> ranked selectors (primary first, then fallbacks).
const LOCATORS = {
    'user_field': ['android=new UiSelector().resourceId("user_field")', '//input[1]'],
    'login_btn': ['~login_btn'],
    'Welcome': ['android=new UiSelector().text("Welcome")'],
};

// Resolve a friendly target to an element via its ranked selectors (self-healing).
async function find(target) {
    for (const selector of LOCATORS[target]) {
        const el = await driver.$(selector);
        if (await el.isExisting()) {
            return el;
        }
    }
    throw new Error(`No locator matched for target: ${target}`);
}

Given('the app is launched', async () => {
    await driver.activateApp(APP_PACKAGE);
});

When('I enter {string} into {string}', async (text, target) => {
    await (await find(target)).setValue(text);
});

When('I tap {string}', async (target) => {
    await (await find(target)).click();
});

When('I wait {int} seconds', async (seconds) => {
    await driver.pause(seconds * 1000);
});

When('I press back', async () => {
    await driver.back();
});

Then('{string} is visible', async (target) => {
    await expect(await find(target)).toBeDisplayed();
});

Then('{string} text is {string}', async (target, expected) => {
    await expect(await find(target)).toHaveText(expected);
});

Then('{string} is enabled', async (target) => {
    await expect(await find(target)).toBeEnabled();
});
