/*
 * LoginFlowTest — auto-generated by Mobile Test Recorder.
 * Generated login flow used for golden tests.
 * Android instrumented (Espresso) test for com.example.app.
 * Place under src/androidTest/. Espresso runs on-device against the real view
 * hierarchy — no Appium driver. XPath locators and runtime fallback chains have
 * no Espresso equivalent and are annotated inline where they occur.
 * DO NOT EDIT BY HAND — regenerate from the recorded flow instead.
 */
package generated

import androidx.test.espresso.Espresso.onView
import androidx.test.espresso.Espresso.pressBack
import androidx.test.espresso.action.ViewActions.click
import androidx.test.espresso.action.ViewActions.closeSoftKeyboard
import androidx.test.espresso.action.ViewActions.typeText
import androidx.test.espresso.assertion.ViewAssertions.matches
import androidx.test.espresso.matcher.ViewMatchers.isDisplayed
import androidx.test.espresso.matcher.ViewMatchers.isEnabled
import androidx.test.espresso.matcher.ViewMatchers.withClassName
import androidx.test.espresso.matcher.ViewMatchers.withContentDescription
import androidx.test.espresso.matcher.ViewMatchers.withId
import androidx.test.espresso.matcher.ViewMatchers.withText
import androidx.test.ext.junit.rules.ActivityScenarioRule
import androidx.test.ext.junit.runners.AndroidJUnit4
import org.hamcrest.Matchers.equalTo
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith
import com.example.app.MainActivity
import com.example.app.R

@RunWith(AndroidJUnit4::class)
class LoginFlowTest {

    @get:Rule
    val scenarioRule = ActivityScenarioRule(MainActivity::class.java)

    @Test
    fun login() {
        // Open app
        // (app launched by ActivityScenarioRule above)
        // Enter email
        onView(withId(R.id.user_field)).perform(typeText("alice@example.com"), closeSoftKeyboard())
        // Tap login
        onView(withContentDescription("login_btn")).perform(click())
        // Wait for home
        // (Espresso auto-synchronizes with the UI thread; explicit wait omitted)
        // Dismiss a dialog
        pressBack()
        // Welcome message shown
        onView(withText("Welcome")).check(matches(isDisplayed()))
    }

}
