"""
LoginFlow — auto-generated by Mobile Test Recorder.
Generated login flow used for golden tests.
App under test: com.example.app
DO NOT EDIT BY HAND — regenerate from the recorded flow instead.
"""

import pytest
from appium import webdriver
from appium.options.android import UiAutomator2Options
from appium.webdriver.common.appiumby import AppiumBy
from selenium.common.exceptions import NoSuchElementException


def _find(driver, primary, fallbacks):
    """Locate an element, falling back through ranked alternatives (self-healing)."""
    for by, value in [primary, *fallbacks]:
        try:
            return driver.find_element(by, value)
        except NoSuchElementException:
            continue
    by, value = primary
    raise NoSuchElementException(
        f"None of the locators matched (primary + {len(fallbacks)} fallbacks): {by}={value}"
    )


@pytest.fixture()
def driver():
    options = UiAutomator2Options()
    options.platform_name = "Android"
    options.app_package = "com.example.app"
    options.app_activity = ".MainActivity"
    drv = webdriver.Remote("http://localhost:4723", options=options)
    yield drv
    drv.quit()


def test_login(driver):
    """User can log in with valid credentials"""
    # Open app
    driver.activate_app("com.example.app")
    # Enter email
    _find(driver, (AppiumBy.ID, "user_field"), [(AppiumBy.XPATH, "//input[1]")]).send_keys("alice@example.com")
    # Tap login
    _find(driver, (AppiumBy.ACCESSIBILITY_ID, "login_btn"), []).click()
    # Wait for home
    driver.implicitly_wait(3)
    # Dismiss a dialog
    driver.back()
    # Welcome message shown
    assert _find(driver, (AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Welcome\")"), []).is_displayed()

