/*
 * LoginFlow — auto-generated by Mobile Test Recorder.
 * Generated login flow used for golden tests.
 * App under test: com.example.app
 * DO NOT EDIT BY HAND — regenerate from the recorded flow instead.
 */
package generated

import io.appium.java_client.AppiumBy
import io.appium.java_client.android.AndroidDriver
import io.appium.java_client.android.options.UiAutomator2Options
import org.junit.jupiter.api.AfterEach
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import org.openqa.selenium.By
import org.openqa.selenium.NoSuchElementException
import org.openqa.selenium.WebElement
import java.net.URL
import java.time.Duration

class LoginFlow {

    private lateinit var driver: AndroidDriver

    @BeforeEach
    fun setUp() {
        val options = UiAutomator2Options()
        options.setPlatformName("Android")
        options.setAppPackage("com.example.app")
        options.setAppActivity(".MainActivity")
        driver = AndroidDriver(URL("http://localhost:4723"), options)
    }

    @AfterEach
    fun tearDown() {
        driver.quit()
    }

    /** Locate an element, falling back through ranked alternatives (self-healing). */
    private fun find(primary: By, fallbacks: Array<By>): WebElement {
        try {
            return driver.findElement(primary)
        } catch (ignored: NoSuchElementException) {
        }
        for (by in fallbacks) {
            try {
                return driver.findElement(by)
            } catch (ignored: NoSuchElementException) {
            }
        }
        throw NoSuchElementException("No locator matched (primary + ${fallbacks.size} fallbacks)")
    }

    @Test
    fun login() {
        // Open app
        driver.activateApp("com.example.app")
        // Enter email
        find(AppiumBy.id("user_field"), arrayOf(AppiumBy.xpath("//input[1]"))).sendKeys("alice@example.com")
        // Tap login
        find(AppiumBy.accessibilityId("login_btn"), arrayOf()).click()
        // Wait for home
        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3))
        // Dismiss a dialog
        driver.navigate().back()
        // Welcome message shown
        Assertions.assertTrue(find(AppiumBy.androidUIAutomator("new UiSelector().text(\"Welcome\")"), arrayOf()).isDisplayed)
    }

}
