/*
 * LoginFlow — auto-generated by Mobile Test Recorder.
 * Generated login flow used for golden tests.
 * App under test: com.example.app
 * DO NOT EDIT BY HAND — regenerate from the recorded flow instead.
 *
 * WebdriverIO mobile spec (Mocha). Requires an Appium session configured in
 * wdio.conf.js with app:appPackage = com.example.app.
 */

const APP_PACKAGE = 'com.example.app';

// Locate an element, falling back through ranked selectors (self-healing).
async function find(selectors) {
    for (const selector of selectors) {
        const el = await driver.$(selector);
        if (await el.isExisting()) {
            return el;
        }
    }
    throw new Error(`No selector matched: ${selectors.join(', ')}`);
}

describe('LoginFlow', () => {
    it('login', async () => {
        // Open app
        await driver.activateApp(APP_PACKAGE);
        // Enter email
        await (await find(['android=new UiSelector().resourceId("user_field")', '//input[1]'])).setValue('alice@example.com');
        // Tap login
        await (await find(['~login_btn'])).click();
        // Wait for home
        await driver.pause(3000);
        // Dismiss a dialog
        await driver.back();
        // Welcome message shown
        await expect(await find(['android=new UiSelector().text("Welcome")'])).toBeDisplayed();
    });
});

